language: node_js
node_js:
  - '8'
before_install:
  - openssl aes-256-cbc -K $encrypted_365cdf6f8b27_key -iv $encrypted_365cdf6f8b27_iv
    -in id_rsa_travis.enc -out .travis/id_rsa_travis -d
  - ls
  - pwd
  - cd ~/.ssh
  - pwd
  - chmod 600 ~/.ssh/id_rsa
  # 添加ssh密钥
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  # 添加ssh配置文件
  - cp .travis/ssh_config ~/.ssh/config
  # 设置github账户信息
  - git config --global user.name "bigxigua" #设置github用户名
  - git config --global user.email 13365945839@qq.com #设置github用户邮箱

after_success:
  - ssh ubuntu@118.24.89.72 'cd /var/www/workspace/chat && git pull'

